[package]
org = "ballerina"
name = "data.yaml"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["yaml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.yaml"
license = ["Apache-2.0"]
distribution = "2201.12.0-20250226-081700-17d84e0f"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "yaml-native"
version = "@toml.version@"
path = "../native/build/libs/data.yaml-native-@project.version@.jar"


[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "@constraint.version@"
path = "./lib/constraint-native-@stdlib.constraintnative.version@.jar"
