[package]
org = "ballerina"
name = "data.yaml"
version = "0.7.1"
authors = ["Ballerina"]
keywords = ["yaml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.yaml"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "yaml-native"
version = "0.7.1"
path = "../native/build/libs/data.yaml-native-0.7.1-SNAPSHOT.jar"


[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.6.0"
path = "./lib/constraint-native-1.6.0.jar"
